// Id lists the TypeScript code is typed against, generated from the content files (a JSON import
// cannot give literal types). `npm run content:ids` rewrites content/schemas/ids.generated.ts; a unit
// test fails when it is stale, and the admin dashboard regenerates it on every species save.
// Order is release order, not table order: existing ids keep their place (NPC orders are generated
// in this order) and new ones are appended. An id is never removed (ARCHITECTURE §8).
import { existsSync, readFileSync } from 'node:fs';

export const IDS_FILE = 'content/schemas/ids.generated.ts';

export const ID_LISTS = [
  { name: 'BREED_ID_VALUES', file: 'farm/species.json', key: 'species' },
  { name: 'ITEM_ID_VALUES', file: 'shared/items.json', key: 'items' },
  { name: 'DECOR_ID_VALUES', file: 'farm/decor.json', key: 'decor' },
] as const;

const contentIds = (file: string, key: string): string[] =>
  (JSON.parse(readFileSync(`content/${file}`, 'utf8')) as Record<string, { id: string }[]>)[key]!.map((r) => r.id);

/** The `name` list as written in `text` (empty when absent). */
export function listIn(text: string, name: string): string[] {
  const start = text.indexOf(`export const ${name} = [`);
  if (start < 0) return [];
  const body = text.slice(start, text.indexOf('] as const;', start));
  return [...body.matchAll(/'([A-Z0-9_]+)'/g)].map((m) => m[1]!);
}

/** Text of ids.generated.ts: `previous` order kept, new content ids appended; throws on a removed id. */
export function idsText(previous = existsSync(IDS_FILE) ? readFileSync(IDS_FILE, 'utf8') : ''): string {
  const lists = ID_LISTS.map(({ name, file, key }) => {
    const now = contentIds(file, key);
    const before = listIn(previous, name);
    const removed = before.filter((id) => !now.includes(id));
    if (removed.length > 0) {
      throw new Error(`${file}: ${removed.join(', ')} removed — shipped ids stay; set enabled/active: false instead`);
    }
    const values = [...before, ...now.filter((id) => !before.includes(id))];
    return `export const ${name} = [\n${values.map((v) => `  '${v}',`).join('\n')}\n] as const;\n`;
  });
  return [
    '// GENERATED by `npm run content:ids` from content/*.json: do not edit by hand.',
    '// Release order: new ids are appended, none is ever removed (ARCHITECTURE §8).',
    '',
    ...lists,
  ].join('\n');
}
