export const ERRORS = [
  "INVALID_REQUEST", "PIG_NOT_FOUND", "INSUFFICIENT_GOLD", "INSUFFICIENT_ITEM",
  "PIG_NOT_MATURE", "PIG_IS_SICK", "PIG_IS_PREGNANT", "PIG_NOT_SICK",
  "ALREADY_FULL", "ALREADY_CLEAN", "INVALID_BREEDING_PARTNERS",
  "BREEDING_COMBINATION_NOT_SUPPORTED", "NO_PIG_SLOT",
  "LEVEL_TOO_LOW", "MAX_SLOTS_REACHED", "SAVE_CORRUPT", "SAVE_TOO_NEW",
  "TROUGH_FULL", "SKIN_NOT_OWNED", "SKIN_ALREADY_OWNED", "SKIN_BREED_NOT_ALLOWED",
  "ORDER_NOT_FOUND", "ORDER_EXPIRED", "ORDER_REQUIREMENTS_NOT_MET",
  "GIFT_NOT_FOUND",
] as const;

export type ErrorCode = (typeof ERRORS)[number];
