export const ERRORS = [
  "INVALID_REQUEST", "PIG_NOT_FOUND", "INSUFFICIENT_GOLD", "INSUFFICIENT_ITEM",
  "PIG_NOT_MATURE", "PIG_IS_SICK", "PIG_IS_PREGNANT", "PIG_NOT_SICK",
  "ALREADY_FULL", "ALREADY_CLEAN", "INVALID_BREEDING_PARTNERS",
  "BREEDING_COMBINATION_NOT_SUPPORTED", "NO_PIG_SLOT",
  "LEVEL_TOO_LOW", "MAX_SLOTS_REACHED", "SAVE_CORRUPT", "SAVE_TOO_NEW",
  "TROUGH_FULL",
  "ORDER_NOT_FOUND", "ORDER_EXPIRED", "ORDER_REQUIREMENTS_NOT_MET",
  "GIFT_NOT_FOUND",
  "NOT_STUCK", "DAILY_ALREADY_CLAIMED", "ACHIEVEMENT_LOCKED", "ALREADY_CLAIMED",
  "ALREADY_OWNED",
  "NURSERY_FULL",
  "INVENTORY_FULL",
  "NO_MANURE",
] as const;

export type ErrorCode = (typeof ERRORS)[number];
