// Species rows (UN_IN_PIG_CATALOGUE.md). Written by the admin dashboard (`npm run admin`,
// DECISIONS A7-1); hand edits are fine if they keep one row per line. A missing stat = rarity tier.
import type { SpeciesRow } from './breeds';

export const SPECIES_ROWS: readonly SpeciesRow[] = [
  { id: "PIG_EARTH_PINK", nameVi: "Heo Hồng Đất", rarity: "COMMON", family: "FARM", buyGold: 500, artId: "pig_classic", color: 0xf7a8b8 },
  { id: "PIG_WHITE", nameVi: "Heo Trắng", rarity: "COMMON", family: "FARM", buyGold: 500, artId: "pig_white", color: 0xfff4ea },
  { id: "PIG_BLACK", nameVi: "Heo Đen", rarity: "COMMON", family: "FARM", buyGold: 500, artId: "pig_black", color: 0x3d3540 },
  { id: "PIG_BROWN", nameVi: "Heo Nâu", rarity: "COMMON", family: "FARM", buyGold: 500, unlockLevel: 2, artId: "pig_brown", color: 0xb9744f },
  { id: "PIG_SPOTTED", nameVi: "Heo Đốm", rarity: "COMMON", family: "FARM", buyGold: 500, unlockLevel: 3, artId: "pig_spotted", color: 0xf2c4b0 },
  { id: "PIG_FARMER", nameVi: "Heo Nông Dân", rarity: "COMMON", family: "VIETNAM", buyGold: 500, unlockLevel: 2, artId: "pig_farmer", color: 0xf2b48c },
  { id: "PIG_ICECREAM", nameVi: "Heo Kem", rarity: "COMMON", family: "FOOD", buyGold: 500, unlockLevel: 2, artId: "pig_icecream", color: 0xf9c6d3 },
  { id: "PIG_CHEF", nameVi: "Heo Đầu Bếp", rarity: "COMMON", family: "JOB", buyGold: 500, unlockLevel: 3, artId: "pig_chef", color: 0xfce4e4 },
  { id: "PIG_SLEEPY", nameVi: "Heo Buồn Ngủ", rarity: "COMMON", family: "FUNNY", buyGold: 500, unlockLevel: 3, artId: "pig_sleepy", color: 0x84b4e4 },
  { id: "PIG_GHOST", nameVi: "Heo Ma", rarity: "COMMON", family: "HORROR", buyGold: 500, unlockLevel: 4, artId: "pig_ghost", color: 0xf4f4f8 },
  { id: "PIG_TEACHER", nameVi: "Heo Giáo Viên", rarity: "COMMON", family: "JOB", buyGold: 500, unlockLevel: 4, artId: "pig_teacher", color: 0xb48454 },
  { id: "PIG_KNIGHT", nameVi: "Heo Hiệp Sĩ", rarity: "COMMON", family: "ADVENTURE", buyGold: 500, unlockLevel: 5, artId: "pig_knight", color: 0xb8c0cc },
  { id: "PIG_DETECTIVE", nameVi: "Heo Thám Tử", rarity: "COMMON", family: "JOB", artId: "pig_detective", color: 0x9c9c9c },
  { id: "PIG_BUSINESS", nameVi: "Heo Doanh Nhân", rarity: "COMMON", family: "JOB", artId: "pig_business", color: 0x8a5a40 },
  { id: "PIG_BOBA", nameVi: "Heo Trà Sữa", rarity: "COMMON", family: "FOOD", artId: "pig_boba", color: 0xfcccb4 },
  { id: "PIG_LAZY", nameVi: "Heo Lười", rarity: "COMMON", family: "FUNNY", artId: "pig_lazy", color: 0xfcb4b4 },
  { id: "PIG_ANGRY", nameVi: "Heo Cáu", rarity: "COMMON", family: "FUNNY", artId: "pig_angry", color: 0xe46c54 },
  { id: "PIG_CRYBABY", nameVi: "Heo Mít Ướt", rarity: "COMMON", family: "FUNNY", artId: "pig_crybaby", color: 0xfcb4c4 },
  { id: "PIG_GRANDPA", nameVi: "Heo Ông", rarity: "COMMON", family: "FUNNY", artId: "pig_grandpa", color: 0xb4846c },
  { id: "PIG_PARTY", nameVi: "Heo Quẩy", rarity: "COMMON", family: "FUNNY", artId: "pig_party", color: 0xf7a8c8 },
  { id: "PIG_STRIPED_MELON", nameVi: "Heo Sọc Dưa", rarity: "UNCOMMON", family: "MEADOW", artId: "pig_watermelon", color: 0x8fd18a },
  { id: "PIG_BOAR", nameVi: "Heo Rừng", rarity: "UNCOMMON", family: "WILD", buyGold: 1500, unlockLevel: 3, artId: "pig_boar", color: 0x7a6250 },
  { id: "PIG_SHEEP", nameVi: "Heo Cừu", rarity: "UNCOMMON", family: "MEADOW", buyGold: 1500, unlockLevel: 4, artId: "pig_sheep", color: 0xf5ebdd },
  { id: "PIG_BEE", nameVi: "Heo Ong", rarity: "UNCOMMON", family: "MEADOW", artId: "pig_bee", color: 0xf6c944 },
  { id: "PIG_PENGUIN", nameVi: "Heo Cánh Cụt", rarity: "UNCOMMON", family: "WATER", buyGold: 1800, unlockLevel: 5, artId: "pig_penguin", color: 0x33415c },
  { id: "PIG_BUFFALO", nameVi: "Heo Trâu", rarity: "UNCOMMON", family: "FARM", buyGold: 1500, unlockLevel: 4, artId: "pig_buffalo", color: 0x767e8c },
  { id: "PIG_DEER", nameVi: "Heo Hươu Sao", rarity: "UNCOMMON", family: "MEADOW", artId: "pig_deer", color: 0xce8a52 },
  { id: "PIG_PUMPKIN", nameVi: "Heo Bí Ngô", rarity: "UNCOMMON", family: "MEADOW", artId: "pig_pumpkin", color: 0xf28c28 },
  { id: "PIG_AO_DAI", nameVi: "Heo Áo Dài", rarity: "UNCOMMON", family: "VIETNAM", artId: "pig_ao_dai", color: 0xd8443a },
  { id: "PIG_TET", nameVi: "Heo Tết", rarity: "UNCOMMON", family: "VIETNAM", artId: "pig_tet", color: 0xe0453a },
  { id: "PIG_LAN", nameVi: "Heo Lân", rarity: "UNCOMMON", family: "VIETNAM", artId: "pig_lan", color: 0xb46c54 },
  { id: "PIG_BANH_CHUNG", nameVi: "Heo Bánh Chưng", rarity: "UNCOMMON", family: "VIETNAM", artId: "pig_banh_chung", color: 0x54843c },
  { id: "PIG_ASTRONAUT", nameVi: "Heo Phi Hành Gia", rarity: "UNCOMMON", family: "JOB", artId: "pig_astronaut", color: 0xeef0f4 },
  { id: "PIG_PIRATE", nameVi: "Heo Cướp Biển", rarity: "UNCOMMON", family: "ADVENTURE", artId: "pig_pirate", color: 0x5a3a2a },
  { id: "PIG_NINJA", nameVi: "Heo Ninja", rarity: "UNCOMMON", family: "ADVENTURE", artId: "pig_ninja", color: 0x3c3c54 },
  { id: "PIG_WITCH", nameVi: "Heo Phù Thủy", rarity: "UNCOMMON", family: "ADVENTURE", artId: "pig_witch", color: 0x6a3fa0 },
  { id: "PIG_SURFER", nameVi: "Heo Lướt Sóng", rarity: "UNCOMMON", family: "ADVENTURE", artId: "pig_surfer", color: 0x3c3c3c },
  { id: "PIG_DIVER", nameVi: "Heo Thợ Lặn", rarity: "UNCOMMON", family: "ADVENTURE", artId: "pig_diver", color: 0x3c546c },
  { id: "PIG_ALIEN", nameVi: "Heo Ngoài Hành Tinh", rarity: "UNCOMMON", family: "SCIFI", buyGold: 1800, unlockLevel: 6, artId: "pig_alien", color: 0xcc9ce4 },
  { id: "PIG_MECHA", nameVi: "Heo Mecha", rarity: "UNCOMMON", family: "SCIFI", artId: "pig_mecha", color: 0x9c6c54 },
  { id: "PIG_CYBORG", nameVi: "Heo Cyborg", rarity: "UNCOMMON", family: "SCIFI", artId: "pig_cyborg", color: 0xb8c0cc },
  { id: "PIG_DRAGON", nameVi: "Heo Rồng", rarity: "UNCOMMON", family: "FANTASY", buyGold: 1800, unlockLevel: 7, artId: "pig_dragon", color: 0xfcb454 },
  { id: "PIG_ONI", nameVi: "Heo Oni", rarity: "UNCOMMON", family: "FANTASY", artId: "pig_oni", color: 0xe46c6c },
  { id: "PIG_VAMPIRE", nameVi: "Heo Ma Cà Rồng", rarity: "UNCOMMON", family: "HORROR", artId: "pig_vampire", color: 0xb49ccc },
  { id: "PIG_ZOMBIE", nameVi: "Heo Zombie", rarity: "UNCOMMON", family: "HORROR", artId: "pig_zombie", color: 0x9cb484 },
  { id: "PIG_DONUT", nameVi: "Heo Donut", rarity: "UNCOMMON", family: "FOOD", artId: "pig_donut", color: 0xfc9cb4 },
  { id: "PIG_BURGER", nameVi: "Heo Burger", rarity: "UNCOMMON", family: "FOOD", artId: "pig_burger", color: 0xe49c3c },
  { id: "PIG_RICH", nameVi: "Heo Đại Gia", rarity: "UNCOMMON", family: "FUNNY", artId: "pig_rich", color: 0xfccc9c },
  { id: "PIG_SUPERMAN", nameVi: "Heo Siêu Nhân", rarity: "RARE", family: "HERO", artId: "pig_superhero", color: 0x7fa8f0 },
  { id: "PIG_TIGER", nameVi: "Heo Hổ", rarity: "RARE", family: "WILD", buyGold: 7000, unlockLevel: 6, artId: "pig_tiger", color: 0xf29a4a },
  { id: "PIG_PANDA", nameVi: "Heo Gấu Trúc", rarity: "RARE", family: "WILD", artId: "pig_panda", color: 0xf4f1ee },
  { id: "PIG_AXOLOTL", nameVi: "Heo Kỳ Giông", rarity: "RARE", family: "WATER", buyGold: 7000, unlockLevel: 7, artId: "pig_axolotl", color: 0xffc4d6 },
  { id: "PIG_SUNFLOWER", nameVi: "Heo Hướng Dương", rarity: "RARE", family: "MEADOW", artId: "pig_sunflower", color: 0xf6c62e },
  { id: "PIG_HEDGEHOG", nameVi: "Heo Nhím", rarity: "RARE", family: "WILD", buyGold: 7000, unlockLevel: 8, artId: "pig_hedgehog", color: 0x8a5a3c },
  { id: "PIG_TURTLE", nameVi: "Heo Rùa", rarity: "RARE", family: "WATER", artId: "pig_turtle", color: 0x6a9f56 },
  { id: "PIG_BATTLEBOT", nameVi: "Heo Battlebot", rarity: "RARE", family: "SCIFI", artId: "pig_battlebot", color: 0x9cb4b4 },
  { id: "PIG_UFO", nameVi: "Heo UFO", rarity: "RARE", family: "SCIFI", artId: "pig_ufo", color: 0xb4cce4 },
  { id: "PIG_KITSUNE", nameVi: "Heo Hồ Ly", rarity: "RARE", family: "FANTASY", artId: "pig_kitsune", color: 0xf2a35a },
  { id: "PIG_PEGASUS", nameVi: "Heo Pegasus", rarity: "RARE", family: "FANTASY", artId: "pig_pegasus", color: 0xfcfce4 },
  { id: "PIG_ZEUS", nameVi: "Heo Zeus", rarity: "RARE", family: "FANTASY", artId: "pig_zeus", color: 0xf6d36a },
  { id: "PIG_VALKYRIE", nameVi: "Heo Valkyrie", rarity: "RARE", family: "FANTASY", artId: "pig_valkyrie", color: 0xd9b45a },
  { id: "PIG_THOR", nameVi: "Heo Thor", rarity: "RARE", family: "FANTASY", artId: "pig_thor", color: 0x8a94a6 },
  { id: "PIG_KOI", nameVi: "Heo Cá Chép", rarity: "EPIC", family: "WATER", artId: "pig_koi", color: 0xe8573e },
  { id: "PIG_DRAGONLING", nameVi: "Heo Rồng Con", rarity: "EPIC", family: "MYTHIC", artId: "pig_dragonling", color: 0x5fc2a0 },
  { id: "PIG_GALAXY", nameVi: "Heo Ngân Hà", rarity: "EPIC", family: "MYTHIC", artId: "pig_galaxy", color: 0x3b3a78 },
  { id: "PIG_ROBOT", nameVi: "Heo Robot", rarity: "EPIC", family: "HERO", artId: "pig_robot", color: 0x9aa4b4 },
  { id: "PIG_UNICORN", nameVi: "Heo Kỳ Lân", rarity: "EPIC", family: "MYTHIC", artId: "pig_unicorn", color: 0xffd6e4 },
  { id: "PIG_MYTHICAL", nameVi: "Heo Thần Thoại", rarity: "LEGENDARY", family: "MYTHIC", artId: "pig_thienlong", color: 0xc9a0f0 },
  { id: "PIG_PHOENIX", nameVi: "Heo Phượng Hoàng", rarity: "LEGENDARY", family: "MYTHIC", artId: "pig_phoenix", color: 0xf07a3e },
];
