// Species traits (DECISIONS PS-2): visual / theme tags that steer breeding beyond rarity and
// family — two parents sharing traits are more compatible and favour children with those traits
// (Watermelon × Turtle → green / water pigs; Pegasus × Zeus → sky / light / myth pigs). A new
// species gets one row here; one without a row breeds on rarity and family alone. TUNABLE.
import type { BreedId } from './ids';

export const TRAIT_VALUES = [
  // colour
  'pink', 'white', 'black', 'brown', 'gray', 'gold', 'green', 'red', 'blue', 'purple', 'orange',
  // nature
  'farm', 'animal', 'wild', 'plant', 'fruit', 'flower', 'insect', 'water', 'ice', 'fire', 'sky',
  // theme
  'food', 'sweet', 'job', 'hero', 'warrior', 'magic', 'myth', 'light', 'dark', 'spooky', 'space',
  'tech', 'metal', 'festive', 'vietnam', 'royal', 'funny', 'cozy', 'wings', 'horns',
] as const;
export type Trait = (typeof TRAIT_VALUES)[number];

export const SPECIES_TRAITS: Partial<Record<BreedId, readonly Trait[]>> = {
  PIG_EARTH_PINK: ['pink', 'farm'],
  PIG_WHITE: ['white', 'farm'],
  PIG_BLACK: ['black', 'farm', 'dark'],
  PIG_BROWN: ['brown', 'farm'],
  PIG_SPOTTED: ['brown', 'white', 'farm'],
  PIG_FARMER: ['farm', 'vietnam', 'plant', 'job'],
  PIG_ICECREAM: ['sweet', 'food', 'ice', 'pink'],
  PIG_CHEF: ['food', 'job', 'white'],
  PIG_SLEEPY: ['cozy', 'blue', 'funny'],
  PIG_GHOST: ['spooky', 'white', 'dark'],
  PIG_TEACHER: ['job', 'brown'],
  PIG_KNIGHT: ['warrior', 'metal', 'hero'],
  PIG_DETECTIVE: ['job', 'gray'],
  PIG_BUSINESS: ['job', 'gold'],
  PIG_BOBA: ['food', 'sweet', 'brown'],
  PIG_LAZY: ['cozy', 'funny', 'pink'],
  PIG_ANGRY: ['funny', 'red', 'fire'],
  PIG_CRYBABY: ['funny', 'water', 'pink'],
  PIG_GRANDPA: ['funny', 'cozy', 'gray'],
  PIG_PARTY: ['funny', 'festive'],
  PIG_STRIPED_MELON: ['green', 'fruit', 'plant'],
  PIG_BOAR: ['brown', 'wild', 'animal'],
  PIG_SHEEP: ['white', 'animal', 'cozy'],
  PIG_BEE: ['gold', 'insect', 'flower'],
  PIG_PENGUIN: ['black', 'white', 'water', 'ice'],
  PIG_BUFFALO: ['gray', 'farm', 'animal', 'horns'],
  PIG_DEER: ['brown', 'wild', 'animal', 'horns'],
  PIG_PUMPKIN: ['orange', 'plant', 'fruit', 'spooky'],
  PIG_AO_DAI: ['vietnam', 'red', 'festive'],
  PIG_TET: ['vietnam', 'red', 'festive', 'gold'],
  PIG_LAN: ['vietnam', 'festive', 'myth'],
  PIG_BANH_CHUNG: ['vietnam', 'food', 'green', 'festive'],
  PIG_ASTRONAUT: ['space', 'job', 'white', 'tech'],
  PIG_PIRATE: ['warrior', 'water'],
  PIG_NINJA: ['warrior', 'black', 'dark'],
  PIG_WITCH: ['magic', 'purple', 'spooky'],
  PIG_SURFER: ['water', 'blue'],
  PIG_DIVER: ['water', 'blue', 'tech'],
  PIG_ALIEN: ['space', 'purple'],
  PIG_MECHA: ['tech', 'metal', 'warrior', 'green'],
  PIG_CYBORG: ['tech', 'metal', 'red'],
  PIG_DRAGON: ['myth', 'gold', 'horns', 'fire'],
  PIG_ONI: ['spooky', 'red', 'horns', 'myth'],
  PIG_VAMPIRE: ['spooky', 'purple', 'dark'],
  PIG_ZOMBIE: ['spooky', 'green'],
  PIG_DONUT: ['sweet', 'food', 'pink'],
  PIG_BURGER: ['food', 'orange'],
  PIG_RICH: ['gold', 'funny', 'royal'],
  PIG_SUPERMAN: ['hero', 'purple', 'sky'],
  PIG_TIGER: ['orange', 'wild', 'animal'],
  PIG_PANDA: ['white', 'black', 'wild', 'animal'],
  PIG_AXOLOTL: ['pink', 'water', 'animal'],
  PIG_SUNFLOWER: ['gold', 'flower', 'plant', 'light'],
  PIG_HEDGEHOG: ['brown', 'wild', 'animal'],
  PIG_TURTLE: ['green', 'water', 'animal'],
  PIG_BATTLEBOT: ['tech', 'metal', 'warrior'],
  PIG_UFO: ['space', 'tech', 'sky'],
  PIG_KITSUNE: ['myth', 'magic', 'orange'],
  PIG_PEGASUS: ['myth', 'sky', 'wings', 'light', 'white'],
  PIG_ZEUS: ['myth', 'light', 'royal', 'gold', 'sky'],
  PIG_VALKYRIE: ['myth', 'warrior', 'wings', 'gold'],
  PIG_THOR: ['myth', 'warrior', 'metal', 'sky'],
  PIG_KOI: ['water', 'red', 'gold'],
  PIG_DRAGONLING: ['myth', 'green', 'wings', 'horns'],
  PIG_GALAXY: ['space', 'purple', 'dark', 'magic'],
  PIG_ROBOT: ['tech', 'metal', 'hero'],
  PIG_UNICORN: ['myth', 'magic', 'light', 'horns'],
  PIG_MYTHICAL: ['myth', 'gold', 'wings', 'royal', 'light'],
  PIG_PHOENIX: ['myth', 'fire', 'wings', 'red', 'light'],
};
