// Seasonal environment FX table (DECISIONS MU-2): the emitters of each season (model and admin
// tuning: seasonFx.ts). Spring: petals, butterflies, pollen · summer: sunbeams, sun dust, night
// fireflies · autumn: leaves, warm haze · winter: snow, wind swirls. TUNABLE.
import type { DayPhase } from '../../../../core/config/dayNight';
import type { FxEmitter } from './seasonFx';
import type { SeasonId } from '../../../../core/config/seasons';

const DAYTIME: readonly DayPhase[] = ['morning', 'day', 'afternoon'];
const NIGHT: readonly DayPhase[] = ['night'];
const SPRING_TREES = ['prop_red_tree', 'prop_bush', 'prop_sunflower'];

export const SEASON_FX: Readonly<Record<SeasonId, readonly FxEmitter[]>> = {
  spring: [
    {
      id: 'spring_petals',
      labelVi: 'Cánh hoa đào / mai rơi',
      art: 'fx_env_petals',
      spawnIntervalMs: [700, 1600],
      burst: [1, 3],
      lifetimeMs: [7000, 11000],
      maxActive: 22,
      density: 0.8,
      speed: [26, 46],
      direction: 40, // top-left → bottom-right
      directionJitter: 12,
      sway: { amp: [8, 22], hz: [0.25, 0.6] },
      spin: [-70, 70],
      angle: [0, 360],
      size: [13, 20],
      opacity: [0.7, 0.95],
      fadeMs: 900,
      area: 'top',
      layer: 'air',
    },
    {
      id: 'spring_butterflies',
      labelVi: 'Bướm quanh cây xuân',
      art: 'fx_env_butterflies',
      flap: { size: 2, fps: 7 },
      spawnIntervalMs: [5000, 11000],
      burst: [1, 1],
      lifetimeMs: [9000, 15000],
      maxActive: 3,
      density: 0.7,
      speed: [10, 20],
      direction: 0,
      directionJitter: 180,
      sway: { amp: [10, 22], hz: [0.3, 0.7] },
      spin: [0, 0],
      angle: [-12, 12],
      size: [26, 34],
      opacity: [0.9, 1],
      fadeMs: 1200,
      area: 'anchors',
      anchors: SPRING_TREES,
      anchorSpread: 0.8,
      layer: 'ground',
      phases: ['dawn', ...DAYTIME, 'sunset'],
    },
    {
      id: 'spring_pollen',
      labelVi: 'Phấn hoa lơ lửng',
      art: 'fx_env_glow',
      spawnIntervalMs: [1500, 3000],
      burst: [1, 2],
      lifetimeMs: [5000, 8000],
      maxActive: 10,
      density: 0.6,
      speed: [4, 10],
      direction: -80,
      directionJitter: 40,
      sway: { amp: [4, 10], hz: [0.2, 0.5] },
      spin: [0, 0],
      angle: [0, 0],
      size: [4, 7],
      opacity: [0.35, 0.6],
      fadeMs: 1500,
      tint: [0xfff3a8, 0xffe9c7],
      area: 'view',
      layer: 'air',
      phases: DAYTIME,
    },
  ],
  summer: [
    {
      id: 'summer_sunbeams',
      labelVi: 'Tia nắng',
      art: 'fx_env_sunbeams',
      spawnIntervalMs: [9000, 16000],
      burst: [1, 1],
      lifetimeMs: [9000, 14000],
      maxActive: 2,
      density: 0.8,
      speed: [2, 5],
      direction: 0,
      directionJitter: 10,
      sway: { amp: [0, 0], hz: [0, 0] },
      spin: [0, 0],
      angle: [-4, 4],
      size: [260, 360],
      opacity: [0.35, 0.5],
      fadeMs: 3500,
      blend: 'normal',
      area: 'view',
      layer: 'ground',
      phases: DAYTIME,
    },
    {
      id: 'summer_dust',
      labelVi: 'Bụi nắng / phấn hoa',
      art: 'fx_env_glow',
      spawnIntervalMs: [1200, 2600],
      burst: [1, 2],
      lifetimeMs: [5000, 9000],
      maxActive: 12,
      density: 0.6,
      speed: [3, 9],
      direction: -70,
      directionJitter: 50,
      sway: { amp: [3, 9], hz: [0.15, 0.4] },
      spin: [0, 0],
      angle: [0, 0],
      size: [3, 6],
      opacity: [0.35, 0.65],
      fadeMs: 1500,
      tint: [0xfff3b0, 0xffe27a],
      blend: 'add',
      area: 'view',
      layer: 'air',
      phases: DAYTIME,
    },
    {
      id: 'summer_fireflies',
      labelVi: 'Đom đóm (đêm hè)',
      art: 'fx_env_fireflies',
      spawnIntervalMs: [900, 2200],
      burst: [1, 2],
      lifetimeMs: [6000, 11000],
      maxActive: 14,
      density: 0.85,
      speed: [5, 14],
      direction: 0,
      directionJitter: 180,
      sway: { amp: [6, 16], hz: [0.2, 0.6] },
      spin: [0, 0],
      angle: [0, 0],
      size: [30, 42],
      opacity: [0.75, 1],
      fadeMs: 1200,
      pulse: { depth: 0.65, hz: [0.4, 1.1] },
      blend: 'add',
      area: 'anchors',
      anchors: ['prop_water_well', 'prop_fence_section', 'prop_bush', 'prop_red_tree'],
      anchorSpread: 0.9,
      layer: 'glow',
      phases: NIGHT,
    },
  ],
  autumn: [
    {
      id: 'autumn_leaves',
      labelVi: 'Lá phong / sồi rơi',
      art: 'fx_env_leaves',
      spawnIntervalMs: [900, 2000],
      burst: [1, 2],
      lifetimeMs: [7000, 11000],
      maxActive: 16,
      density: 0.8,
      speed: [30, 55],
      direction: 75,
      directionJitter: 15,
      sway: { amp: [14, 30], hz: [0.3, 0.8] },
      spin: [-150, 150],
      angle: [0, 360],
      size: [18, 28],
      opacity: [0.85, 1],
      fadeMs: 800,
      area: 'top',
      layer: 'air',
    },
    {
      id: 'autumn_haze',
      labelVi: 'Sương ấm',
      art: 'fx_env_haze',
      spawnIntervalMs: [7000, 13000],
      burst: [1, 1],
      lifetimeMs: [16000, 24000],
      maxActive: 3,
      density: 0.8,
      speed: [3, 7],
      direction: 0,
      directionJitter: 20,
      sway: { amp: [0, 0], hz: [0, 0] },
      spin: [0, 0],
      angle: [0, 0],
      size: [420, 620],
      opacity: [0.1, 0.18],
      fadeMs: 5000,
      tint: [0xf2b46a, 0xe8a058],
      area: 'view',
      layer: 'ground',
    },
  ],
  winter: [
    {
      id: 'winter_snow',
      labelVi: 'Tuyết rơi',
      art: 'fx_env_snowflakes',
      spawnIntervalMs: [350, 900],
      burst: [1, 3],
      lifetimeMs: [8000, 13000],
      maxActive: 40,
      density: 0.85,
      speed: [22, 44],
      direction: 82,
      directionJitter: 8,
      sway: { amp: [5, 14], hz: [0.2, 0.55] },
      spin: [-40, 40],
      angle: [0, 360],
      size: [8, 14],
      opacity: [0.65, 0.95],
      fadeMs: 900,
      area: 'top',
      layer: 'air',
    },
    {
      id: 'winter_wind',
      labelVi: 'Gió xoáy quanh chuồng / kho',
      art: 'fx_env_wind',
      spawnIntervalMs: [6000, 12000],
      burst: [1, 1],
      lifetimeMs: [2600, 4000],
      maxActive: 2,
      density: 0.7,
      speed: [26, 44],
      direction: 0,
      directionJitter: 15,
      sway: { amp: [2, 5], hz: [0.3, 0.6] },
      spin: [0, 0],
      angle: [-6, 6],
      size: [90, 130],
      opacity: [0.45, 0.7],
      fadeMs: 900,
      area: 'anchors',
      anchors: ['prop_pig_house', 'prop_hay_shed'],
      anchorSpread: 0.7,
      layer: 'ground',
    },
  ],
};
