// Phaser texture keys of manifest files, shared by every Area scene (they all draw from the same
// texture cache). Pure.

/** `asset` → the id itself; any other file of the row → `${id}_${file}` (e.g. pig_classic_sleep). */
export const textureKey = (id: string, file = 'asset'): string => (file === 'asset' ? id : `${id}_${file}`);

/** The flat picture drawn for an object whose art file is missing (generated by the farm's BootScene). */
export const FALLBACK_PROP_KEY = 'fallback_prop';
